MvcTakip/Controllers/AdminUyeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcTakip.Models;

namespace MvcTakip.Controllers
{
    public class AdminUyeController : Controller
    {
        private mvcTakipDB db = new mvcTakipDB();

        // GET: AdminUye
        public ActionResult Index()
        {
            var tblKisis = db.tblKisis.Include(t => t.tblBolum).Include(t => t.tblYetki);
            return View(tblKisis.OrderByDescending(u=>u.id).ToList());
        }

        // GET: AdminUye/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblKisi tblKisi = db.tblKisis.Find(id);
            if (tblKisi == null)
            {
                return HttpNotFound();
            }
            return View(tblKisi);
        }

        // GET: AdminUye/Create
        public ActionResult Create()
        {
            ViewBag.BolumId = new SelectList(db.tblBolums, "id", "Bolum");
            ViewBag.YetkiId = new SelectList(db.tblYetkis, "id", "Yetki");
            return View();
        }

        // POST: AdminUye/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Adi,Soyadi,CalistigiYer,Agno,MezunYil,Eposta,Sifre,YetkiId,Foto,BolumId,Staj1,Staj2,IsYeriEgitimi")] tblKisi tblKisi)
        {
            if (ModelState.IsValid)
            {
                db.tblKisis.Add(tblKisi);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BolumId = new SelectList(db.tblBolums, "id", "Bolum", tblKisi.BolumId);
            ViewBag.YetkiId = new SelectList(db.tblYetkis, "id", "Yetki", tblKisi.YetkiId);
            return View(tblKisi);
        }

        // GET: AdminUye/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblKisi tblKisi = db.tblKisis.Find(id);
            if (tblKisi == null)
            {
                return HttpNotFound();
            }
            ViewBag.BolumId = new SelectList(db.tblBolums, "id", "Bolum", tblKisi.BolumId);
            ViewBag.YetkiId = new SelectList(db.tblYetkis, "id", "Yetki", tblKisi.YetkiId);
            return View(tblKisi);
        }

        // POST: AdminUye/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Adi,Soyadi,CalistigiYer,Agno,MezunYil,Eposta,Sifre,YetkiId,Foto,BolumId,Staj1,Staj2,IsYeriEgitimi")] tblKisi tblKisi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblKisi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BolumId = new SelectList(db.tblBolums, "id", "Bolum", tblKisi.BolumId);
            ViewBag.YetkiId = new SelectList(db.tblYetkis, "id", "Yetki", tblKisi.YetkiId);
            return View(tblKisi);
        }

        // GET: AdminUye/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblKisi tblKisi = db.tblKisis.Find(id);
            if (tblKisi == null)
            {
                return HttpNotFound();
            }
            return View(tblKisi);
        }

        // POST: AdminUye/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblKisi tblKisi = db.tblKisis.Find(id);
            db.tblKisis.Remove(tblKisi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcTakip/Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcTakip.Models;
using System.Web.Helpers;
using System.IO;

namespace MvcTakip.Controllers
{
    public class UyeController : Controller
    {
        mvcTakipDB db = new mvcTakipDB();
        // GET: Uye
        public ActionResult Index(int id)
        {
            var uye = db.tblKisis.Where(u => u.id == id).SingleOrDefault();
            if (Convert.ToInt32(Session["uyeid"]) != uye.id)
            {
                return HttpNotFound();
            }
            return View(uye);
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(tblKisi uye)
        {
            
            var login = db.tblKisis.Where(u => u.Eposta == uye.Eposta).SingleOrDefault();
            if(login.Eposta == uye.Eposta && login.Sifre == uye.Sifre)
            {
                Session["uyeid"] = login.id;
                Session["email"] = login.Eposta;
                Session["yetkiId"] = login.YetkiId;
                Session["adi"] = login.Adi;
                return RedirectToAction("Index", "Home");

            }
            else
            {
                ViewBag.Uyari = true;
                return View();
            }
            
        }
        public ActionResult Logout()
        {
            Session["uyeid"] = null;
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Create()
        {
            ViewBag.BolumId = new SelectList(db.tblBolums, "id", "Bolum");
            
            return View();
        }
        [HttpPost]
        public ActionResult Create(tblKisi uye, HttpPostedFileBase Foto)
        {
            if (ModelState.IsValid) {
                if (Foto != null) {
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);
                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(150, 150);
                    img.Save("~/Uploads/MezunFoto/" + newfoto);
                    uye.Foto = "/Uploads/MezunFoto/" + newfoto;
                    uye.YetkiId = 2;
                    db.tblKisis.Add(uye);
                    db.SaveChanges();
                    Session["uyeid"] = uye.id;
                    Session["email"] = uye.Eposta;
                    Session["adi"] = uye.Adi;
                    return RedirectToAction("Index", "Home");

                }
                else
                {
                    ModelState.AddModelError("Fotograf", "Fotograf Seciniz");
                }
            }
            return View(uye);
        }
        public ActionResult Edit(int id)
        {
            var uye = db.tblKisis.Where(u => u.id == id).SingleOrDefault();
            if (Convert.ToInt32(Session["uyeid"]) != uye.id)
            {
                return HttpNotFound();
            }
            
            return View(uye);
        }
        [HttpPost]
        public ActionResult Edit(tblKisi uye, int id, HttpPostedFileBase Foto)
        {
            if (ModelState.IsValid)
            {
                var uyes = db.tblKisis.Where(u => u.id == id).SingleOrDefault();
                if (Foto != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(uye.Foto)))
                    {
                        System.IO.File.Delete(Server.MapPath(uyes.Foto));
                    }
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo fotoinfo = new FileInfo(Foto.FileName);

                    string newfoto = Guid.NewGuid().ToString() + fotoinfo.Extension;
                    img.Resize(150, 150);
                    img.Save("~/Uploads/MezunFoto/" + newfoto);
                    uyes.Foto = "/Uploads/MezunFoto/" + newfoto;
                }
                uyes.Adi = uye.Adi;
                uyes.Soyadi = uye.Soyadi;
                uyes.Eposta = uye.Eposta;
                uyes.Sifre = uye.Sifre;
                uyes.CalistigiYer = uye.CalistigiYer;
                db.SaveChanges();

                Session["adi"] = uye.Adi;
                Session["uyeid"] = uye.id;
                return RedirectToAction("Index", "Home", new { id = uyes.id });
            }
            return View();
        }
    }
}

MvcTakip/Views/AdminUye/Create.cshtml
@model MvcTakip.Models.tblKisi

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="adminUyeCreate">
<h2 style="color:gray;">Yeni Mezun Ekle</h2>


@using (Html.BeginForm("Create", "Uye", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.BolumId, "Bölümün Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BolumId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BolumId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Foto, "Fotoğraf" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Foto" id="Foto" value="" accept=".jpg,.png,.gif,.JPEG,.jpeg" class="form-control">
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adi, "Adı" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soyadi, "Soyadı" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soyadi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soyadi, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Eposta, htmlAttributes: new { @class = "control-label col-md-2", @type = "email" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Eposta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Eposta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sifre, "Şifre" ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Staj1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Staj1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Staj1, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Staj2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Staj2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Staj2, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsYeriEgitimi, "İşyeri Eğitimi" ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsYeriEgitimi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsYeriEgitimi, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.CalistigiYer, "Çalıştığı Firma/Kurum" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CalistigiYer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CalistigiYer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Agno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Agno, new { htmlAttributes = new { @class = "form-control" , @placeholder = "Örneğin (0,00)" } })
                @Html.ValidationMessageFor(model => model.Agno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MezunYil, "Mezun Olduğu Yıl " ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MezunYil, new { htmlAttributes = new { @class = "form-control", @placeholder = "Örneğin (2019)" } })
                @Html.ValidationMessageFor(model => model.MezunYil, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Yeni Kayıt" class="btn btn-success" />
            </div>
        </div>
    </div>
}



<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>
</div>

<style>
    .adminUyeCreate{
        margin-left:30px;
        margin-right:30px;
    }
</style>

MvcTakip/Views/AdminUye/Delete.cshtml
@model MvcTakip.Models.tblKisi

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<h3 class="silText">Kişiyi Silmek İstediğinize Emin misiniz?</h3>
<hr />


 @*
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tblBolum.Bolum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblBolum.Bolum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblYetki.Yetki)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblYetki.Yetki)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Soyadi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soyadi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CalistigiYer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CalistigiYer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MezunYil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MezunYil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Eposta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Eposta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sifre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sifre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Staj1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Staj1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Staj2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Staj2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsYeriEgitimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsYeriEgitimi)
        </dd>

    </dl>
     *@
    <div class="detail">
     
        <div class="container">
            <div class="row">
                <div class="footer">
                    <p class="adi">@Model.Adi @Model.Soyadi </p>
                    <p class="bolum">@Model.tblBolum.Bolum </p>
                </div>
            </div>
            <br>

            <div class="row">
                <div class="col-md-3">
                    <div class="row">
                        <img class="user-img" height="120" width="120" src="@Model.Foto" alt="">
                    </div>
                    <div class="row">
                        <span class="link">
                            <a href="https://www.linkedin.com/in/mert-demir-6784b4168/" style="text-decoration: none;" target="_blank"><i class="fab fa-linkedin-in"> </i> </a>
                            <a href="https://www.mert.demir96@hotmail.com/" style="text-decoration: none;" target="_blank"> <i class="far fa-envelope"></i></a>
                        </span>
                    </div>

                </div>
                <div class="col-md-9">
                    <p><strong>Mezun Yılı :</strong> @Model.MezunYil <strong style="margin-left:20px;"> AGNO :</strong> @Model.Agno</p>
                    <hr>
                    <p><strong>Staj 1 :</strong> @Model.Staj1</p>
                    <p><strong>Staj 2 :</strong> @Model.Staj2</p>
                    <p><strong>İş Yeri Eğitimi :</strong> @Model.IsYeriEgitimi</p>
                    <p><strong>Çalıştığı Şirket :</strong> @Model.CalistigiYer</p>
                    <hr>
                    <p><strong>E-Posta :</strong> @Model.Eposta</p>
                </div>
            </div>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Sil" class="btn btn-danger" /> |
                @Html.ActionLink("Geri Dön", "Index")
            </div>
        }
    </div>
  
<style scoped>
    .detail {
        margin-left: 20px;
        margin-top: 20px;
    }

    .link {
        margin-top: 20px;
        margin-left: 90px;
    }

    .row .footer {
        height: 125px;
        background-color: #343a40 !important;
        color: #fff;
        margin-top: 0px;
        margin-right: 0px;
        margin-bottom: 0px;
        margin-left: 0px;
        padding-top: 0px;
        padding-right: 0px;
        padding-bottom: 0px;
        padding-left: 0px;
    }

    .footer {
        display: table;
        table-layout: fixed;
        width: 100%;
        padding-top: 40px;
        padding-right: 0px;
        padding-bottom: 34px;
        padding-left: 0px;
    }

        .footer .adi {
            font-size: 30px;
            font-weight: 400;
            line-height: 1.287;
            margin-top: 20px;
            margin-right: 0px;
            margin-bottom: 0px;
            margin-left: 50px;
        }

        .footer .bolum {
            font-size: 18px;
            font-weight: 400;
            line-height: 1.287;
            margin-top: 7px;
            margin-right: 0px;
            margin-bottom: 0px;
            margin-left: 50px;
        }

    .user-img {
        border-top-left-radius: 50%;
        border-top-right-radius: 50%;
        border-bottom-right-radius: 50%;
        border-bottom-left-radius: 50%;
        display: inline-block;
        position: relative;
        max-width: 100%;
        vertical-align: middle;
        border-top-color: initial;
        border-top-style: initial;
        border-top-width: 0px;
        border-right-color: initial;
        border-right-style: initial;
        border-right-width: 0px;
        border-bottom-color: initial;
        border-bottom-style: initial;
        border-bottom-width: 0px;
        border-left-color: initial;
        border-left-style: initial;
        border-left-width: 0px;
        border-image-source: initial;
        border-image-slice: initial;
        border-image-width: initial;
        border-image-outset: initial;
        border-image-repeat: initial;
        box-sizing: border-box;
        margin-left: 50px;
    }
    .silText{
        margin-left:20px;
    }
</style>

MvcTakip/Views/AdminUye/Details.cshtml
@model MvcTakip.Models.tblKisi

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="detail">
    <h2>Kişi Bilgileri</h2>
    <hr>
    <div class="container">
        <div class="row">
            <div class="footer">
                <p class="adi">@Model.Adi @Model.Soyadi </p>
                <p class="bolum">@Model.tblBolum.Bolum </p>
            </div>
        </div>
        <br>

        <div class="row">
            <div class="col-md-3">
                <div class="row">
                    <img class="user-img" height="120" width="120" src="@Model.Foto" alt="">
                </div>
                <div class="row">
                    <span class="link">
                        <a href="https://www.linkedin.com/in/mert-demir-6784b4168/" style="text-decoration: none;" target="_blank"><i class="fab fa-linkedin-in"> </i> </a>
                        <a href="https://www.mert.demir96@hotmail.com/" style="text-decoration: none;" target="_blank"> <i class="far fa-envelope"></i></a>
                    </span>
                </div>

            </div>
            <div class="col-md-9">
                <p><strong>Mezun Yılı :</strong> @Model.MezunYil <strong style="margin-left:20px;"> AGNO :</strong> @Model.Agno</p>
                <hr>
                <p><strong>Staj 1 :</strong> @Model.Staj1</p>
                <p><strong>Staj 2 :</strong> @Model.Staj2</p>
                <p><strong>İş Yeri Eğitimi :</strong> @Model.IsYeriEgitimi</p>
                <p><strong>Çalıştığı Şirket :</strong> @Model.CalistigiYer</p>
                <hr>
                <p><strong>E-Posta :</strong> @Model.Eposta</p>
            </div>
        </div>
    </div>



    <p>

        @Html.ActionLink("Geri Dön", "Index")
    </p>
</div>
<!--
<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tblBolum.Bolum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblBolum.Bolum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Soyadi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soyadi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CalistigiYer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CalistigiYer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MezunYil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MezunYil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Eposta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Eposta)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            <img class="card-img-top" src="@Model.Foto" style="width:75px; height:75px">
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Staj1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Staj1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Staj2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Staj2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsYeriEgitimi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsYeriEgitimi)
        </dd>

    </dl>
</div>
    -->

<style scoped>
    .detail{
        margin-left:20px;
        margin-top:20px;
    }
    .link {
        margin-top: 20px;
        margin-left: 90px;
    }

    .row .footer {
        height:125px;
        background-color: #343a40 !important;
        color: #fff;
        margin-top: 0px;
        margin-right: 0px;
        margin-bottom: 0px;
        margin-left: 0px;
        padding-top: 0px;
        padding-right: 0px;
        padding-bottom: 0px;
        padding-left: 0px;
    }

    .footer {
        display: table;
        table-layout: fixed;
        width: 100%;
        padding-top: 40px;
        padding-right: 0px;
        padding-bottom: 34px;
        padding-left: 0px;
    }

        .footer .adi {
            font-size: 30px;
            font-weight: 400;
            line-height: 1.287;
            margin-top: 20px;
            margin-right: 0px;
            margin-bottom: 0px;
            margin-left: 50px;
        }

        .footer .bolum {
            font-size: 18px;
            font-weight: 400;
            line-height: 1.287;
            margin-top: 7px;
            margin-right: 0px;
            margin-bottom: 0px;
            margin-left: 50px;
        }

    .user-img {
        border-top-left-radius: 50%;
        border-top-right-radius: 50%;
        border-bottom-right-radius: 50%;
        border-bottom-left-radius: 50%;
        display: inline-block;
        position: relative;
        max-width: 100%;
        vertical-align: middle;
        border-top-color: initial;
        border-top-style: initial;
        border-top-width: 0px;
        border-right-color: initial;
        border-right-style: initial;
        border-right-width: 0px;
        border-bottom-color: initial;
        border-bottom-style: initial;
        border-bottom-width: 0px;
        border-left-color: initial;
        border-left-style: initial;
        border-left-width: 0px;
        border-image-source: initial;
        border-image-slice: initial;
        border-image-width: initial;
        border-image-outset: initial;
        border-image-repeat: initial;
        box-sizing: border-box;
        margin-left: 50px;
    }
</style>